on: push

jobs:
  push:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Chocolatey pack
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: pack
    - name: Move file
      run: mv .\tiled.*.nupkg tiled.nupkg
    - name: Chocolatey push
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: push .\tiled.nupkg --api-key ${{ secrets.CHOCOLATEY_API_KEY }}